name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-05"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmRlNDAwNjgtNTgzOS00ODBjLWJhODAtNzBhNzc4NDY4ZjJkIiwidGVuYW50X2lkIjoiZjQwMDk3MjIzMjMyMmU4OTUxMTQ4YzVmNzgwZTUyNzEyODNhYTNlMTZmNDFhODUyZGZlZGE5NjdkYTNjM2MwMSIsImludGVybmFsX3NlY3JldCI6IjM4OGFmYWE4LWRlOTctNGM5My1hY2IyLWIyZTNkNGE0Yjk2OCJ9.eqTd3s7D0-VSqoEonU_MeSCQFr9twiilRZ19nyOmrI0"
JWT_SECRET = "1234567890"


